defaults: &defaults
  clear: true
  root: "~/code/<%= ENV['TMUX_PROJECT'] %>"
  splits:
    - ""

session:
  name: "<%= ENV['TMUX_PROJECT'] %>"
  windows:
    - name: "server"
      <<: *defaults
    - name: "tests"
      <<: *defaults
    - name: "linter"
      <<: *defaults
    - name: "vim"
      <<: *defaults
      focus: true
      splits:
        - cmd: "nvim -c 'cd ~/code/<%= ENV['TMUX_PROJECT'] %>'"
    - name: "git"
      <<: *defaults
      splits:
        - cmd: "git status"
    - name: "shell 1"
      <<: *defaults
    - name: "shell 2"
      <<: *defaults
    - name: "watch"
      <<: *defaults
